insert into public.sic_codes (code, description, category, subcategory) values
  ('0100', 'AGRICULTURAL PRODUCTION-CROPS', 'Agriculture, Forestry & Fishing', 'Agricultural Production'),
  ('0200', 'AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES', 'Agriculture, Forestry & Fishing', 'Agricultural Production'),
  ('0700', 'AGRICULTURAL SERVICES', 'Agriculture, Forestry & Fishing', 'Agricultural Services'),
  ('0800', 'FORESTRY', 'Agriculture, Forestry & Fishing', 'Forestry & Fishing'),
  ('0900', 'FISHING, HUNTING AND TRAPPING', 'Agriculture, Forestry & Fishing', 'Forestry & Fishing'),
  ('1000', 'METAL MINING', 'Mining & Extraction', 'Metal Mining'),
  ('1040', 'GOLD AND SILVER ORES', 'Mining & Extraction', 'Metal Mining'),
  ('1090', 'MISCELLANEOUS METAL ORES', 'Mining & Extraction', 'Metal Mining'),
  ('1220', 'BITUMINOUS COAL & LIGNITE MINING', 'Mining & Extraction', 'Coal Mining'),
  ('1221', 'BITUMINOUS COAL & LIGNITE SURFACE MINING', 'Mining & Extraction', 'Coal Mining'),
  ('1311', 'CRUDE PETROLEUM & NATURAL GAS', 'Mining & Extraction', 'Oil & Gas Extraction'),
  ('1381', 'DRILLING OIL & GAS WELLS', 'Mining & Extraction', 'Oil & Gas Extraction'),
  ('1382', 'OIL & GAS FIELD EXPLORATION SERVICES', 'Mining & Extraction', 'Oil & Gas Extraction'),
  ('1389', 'OIL & GAS FIELD SERVICES, NEC', 'Mining & Extraction', 'Oil & Gas Extraction'),
  ('1400', 'MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)', 'Mining & Extraction', 'Nonmetallic Minerals'),
  ('1520', 'GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS', 'Construction', 'General Building Contractors'),
  ('1531', 'OPERATIVE BUILDERS', 'Construction', 'General Building Contractors'),
  ('1540', 'GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS', 'Construction', 'General Building Contractors'),
  ('1600', 'HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS', 'Construction', 'Heavy Construction'),
  ('1623', 'WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION', 'Construction', 'Heavy Construction'),
  ('1700', 'CONSTRUCTION - SPECIAL TRADE CONTRACTORS', 'Construction', 'Special Trade Contractors'),
  ('1731', 'ELECTRICAL WORK', 'Construction', 'Special Trade Contractors'),
  ('2000', 'FOOD AND KINDRED PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2011', 'MEAT PACKING PLANTS', 'Manufacturing', 'Food & Beverages'),
  ('2013', 'SAUSAGES & OTHER PREPARED MEAT PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2015', 'POULTRY SLAUGHTERING AND PROCESSING', 'Manufacturing', 'Food & Beverages'),
  ('2020', 'DAIRY PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2024', 'ICE CREAM & FROZEN DESSERTS', 'Manufacturing', 'Food & Beverages'),
  ('2030', 'CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES', 'Manufacturing', 'Food & Beverages'),
  ('2033', 'CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES', 'Manufacturing', 'Food & Beverages'),
  ('2040', 'GRAIN MILL PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2050', 'BAKERY PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2052', 'COOKIES & CRACKERS', 'Manufacturing', 'Food & Beverages'),
  ('2060', 'SUGAR & CONFECTIONERY PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2070', 'FATS & OILS', 'Manufacturing', 'Food & Beverages'),
  ('2080', 'BEVERAGES', 'Manufacturing', 'Food & Beverages'),
  ('2082', 'MALT BEVERAGES', 'Manufacturing', 'Food & Beverages'),
  ('2086', 'BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS', 'Manufacturing', 'Food & Beverages'),
  ('2090', 'MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2092', 'PREPARED FRESH OR FROZEN FISH & SEAFOODS', 'Manufacturing', 'Food & Beverages'),
  ('2100', 'TOBACCO PRODUCTS', 'Manufacturing', 'Food & Beverages'),
  ('2111', 'CIGARETTES', 'Manufacturing', 'Food & Beverages'),
  ('2200', 'TEXTILE MILL PRODUCTS', 'Manufacturing', 'Textiles & Apparel'),
  ('2211', 'BROADWOVEN FABRIC MILLS, COTTON', 'Manufacturing', 'Textiles & Apparel'),
  ('2221', 'BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK', 'Manufacturing', 'Textiles & Apparel'),
  ('2250', 'KNITTING MILLS', 'Manufacturing', 'Textiles & Apparel'),
  ('2253', 'KNIT OUTERWEAR MILLS', 'Manufacturing', 'Textiles & Apparel'),
  ('2273', 'CARPETS & RUGS', 'Manufacturing', 'Textiles & Apparel'),
  ('2300', 'APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL', 'Manufacturing', 'Textiles & Apparel'),
  ('2320', 'MEN''S & BOYS'' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS', 'Manufacturing', 'Textiles & Apparel'),
  ('2330', 'WOMEN''S, MISSES'', AND JUNIORS OUTERWEAR', 'Manufacturing', 'Textiles & Apparel'),
  ('2340', 'WOMEN''S, MISSES'', CHILDREN''S & INFANTS'' UNDERGARMENTS', 'Manufacturing', 'Textiles & Apparel'),
  ('2390', 'MISCELLANEOUS FABRICATED TEXTILE PRODUCTS', 'Manufacturing', 'Textiles & Apparel'),
  ('2400', 'LUMBER & WOOD PRODUCTS (NO FURNITURE)', 'Manufacturing', 'Paper & Chemicals'),
  ('2421', 'SAWMILLS & PLANTING MILLS, GENERAL', 'Manufacturing', 'Paper & Chemicals'),
  ('2430', 'MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS', 'Manufacturing', 'Paper & Chemicals'),
  ('2451', 'MOBILE HOMES', 'Manufacturing', 'Paper & Chemicals'),
  ('2452', 'PREFABRICATED WOOD BLDGS & COMPONENTS', 'Manufacturing', 'Paper & Chemicals'),
  ('2510', 'HOUSEHOLD FURNITURE', 'Manufacturing', 'Paper & Chemicals'),
  ('2511', 'WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)', 'Manufacturing', 'Paper & Chemicals'),
  ('2520', 'OFFICE FURNITURE', 'Manufacturing', 'Paper & Chemicals'),
  ('2522', 'OFFICE FURNITURE (NO WOOD)', 'Manufacturing', 'Paper & Chemicals'),
  ('2531', 'PUBLIC BLDG & RELATED FURNITURE', 'Manufacturing', 'Paper & Chemicals'),
  ('2540', 'PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES', 'Manufacturing', 'Paper & Chemicals'),
  ('2590', 'MISCELLANEOUS FURNITURE & FIXTURES', 'Manufacturing', 'Paper & Chemicals'),
  ('2600', 'PAPERS & ALLIED PRODUCTS', 'Manufacturing', 'Paper & Chemicals'),
  ('2611', 'PULP MILLS', 'Manufacturing', 'Paper & Chemicals'),
  ('2621', 'PAPER MILLS', 'Manufacturing', 'Paper & Chemicals'),
  ('2631', 'PAPERBOARD MILLS', 'Manufacturing', 'Paper & Chemicals'),
  ('2650', 'PAPERBOARD CONTAINERS & BOXES', 'Manufacturing', 'Paper & Chemicals'),
  ('2670', 'CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)', 'Manufacturing', 'Paper & Chemicals'),
  ('2673', 'PLASTICS, FOIL & COATED PAPER BAGS', 'Manufacturing', 'Paper & Chemicals'),
  ('2711', 'NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING', 'Manufacturing', 'Paper & Chemicals'),
  ('2721', 'PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING', 'Manufacturing', 'Paper & Chemicals'),
  ('2731', 'BOOKS: PUBLISHING OR PUBLISHING & PRINTING', 'Manufacturing', 'Paper & Chemicals'),
  ('2732', 'BOOK PRINTING', 'Manufacturing', 'Paper & Chemicals'),
  ('2741', 'MISCELLANEOUS PUBLISHING', 'Manufacturing', 'Paper & Chemicals'),
  ('2750', 'COMMERCIAL PRINTING', 'Manufacturing', 'Paper & Chemicals'),
  ('2761', 'MANIFOLD BUSINESS FORMS', 'Manufacturing', 'Paper & Chemicals'),
  ('2771', 'GREETING CARDS', 'Manufacturing', 'Paper & Chemicals'),
  ('2780', 'BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK', 'Manufacturing', 'Paper & Chemicals'),
  ('2790', 'SERVICE INDUSTRIES FOR THE PRINTING TRADE', 'Manufacturing', 'Paper & Chemicals'),
  ('2800', 'CHEMICALS & ALLIED PRODUCTS', 'Manufacturing', 'Paper & Chemicals'),
  ('2810', 'INDUSTRIAL INORGANIC CHEMICALS', 'Manufacturing', 'Paper & Chemicals'),
  ('2820', 'PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)', 'Manufacturing', 'Paper & Chemicals'),
  ('2821', 'PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS', 'Manufacturing', 'Paper & Chemicals'),
  ('2833', 'MEDICINAL CHEMICALS & BOTANICAL PRODUCTS', 'Manufacturing', 'Paper & Chemicals'),
  ('2834', 'PHARMACEUTICAL PREPARATIONS', 'Manufacturing', 'Paper & Chemicals'),
  ('2835', 'IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES', 'Manufacturing', 'Paper & Chemicals'),
  ('2836', 'BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)', 'Manufacturing', 'Paper & Chemicals'),
  ('2840', 'SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS', 'Manufacturing', 'Paper & Chemicals'),
  ('2842', 'SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS', 'Manufacturing', 'Paper & Chemicals'),
  ('2844', 'PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS', 'Manufacturing', 'Paper & Chemicals'),
  ('2851', 'PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS', 'Manufacturing', 'Paper & Chemicals'),
  ('2860', 'INDUSTRIAL ORGANIC CHEMICALS', 'Manufacturing', 'Paper & Chemicals'),
  ('2870', 'AGRICULTURAL CHEMICALS', 'Manufacturing', 'Paper & Chemicals'),
  ('2890', 'MISCELLANEOUS CHEMICAL PRODUCTS', 'Manufacturing', 'Paper & Chemicals'),
  ('2891', 'ADHESIVES & SEALANTS', 'Manufacturing', 'Paper & Chemicals'),
  ('2911', 'PETROLEUM REFINING', 'Manufacturing', 'Petroleum & Rubber'),
  ('2950', 'ASPHALT PAVING & ROOFING MATERIALS', 'Manufacturing', 'Petroleum & Rubber'),
  ('2990', 'MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL', 'Manufacturing', 'Petroleum & Rubber'),
  ('3011', 'TIRES & INNER TUBES', 'Manufacturing', 'Petroleum & Rubber'),
  ('3021', 'RUBBER & PLASTICS FOOTWEAR', 'Manufacturing', 'Petroleum & Rubber'),
  ('3050', 'GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE', 'Manufacturing', 'Petroleum & Rubber'),
  ('3060', 'FABRICATED RUBBER PRODUCTS, NEC', 'Manufacturing', 'Petroleum & Rubber'),
  ('3080', 'MISCELLANEOUS PLASTICS PRODUCTS', 'Manufacturing', 'Petroleum & Rubber'),
  ('3081', 'UNSUPPORTED PLASTICS FILM & SHEET', 'Manufacturing', 'Petroleum & Rubber'),
  ('3086', 'PLASTICS FOAM PRODUCTS', 'Manufacturing', 'Petroleum & Rubber'),
  ('3089', 'PLASTICS PRODUCTS, NEC', 'Manufacturing', 'Petroleum & Rubber'),
  ('3100', 'LEATHER & LEATHER PRODUCTS', 'Manufacturing', 'Petroleum & Rubber'),
  ('3140', 'FOOTWEAR, (NO RUBBER)', 'Manufacturing', 'Petroleum & Rubber'),
  ('3211', 'FLAT GLASS', 'Manufacturing', 'Metal & Machinery'),
  ('3220', 'GLASS & GLASSWARE, PRESSED OR BLOWN', 'Manufacturing', 'Metal & Machinery'),
  ('3221', 'GLASS CONTAINERS', 'Manufacturing', 'Metal & Machinery'),
  ('3231', 'GLASS PRODUCTS, MADE OF PURCHASED GLASS', 'Manufacturing', 'Metal & Machinery'),
  ('3241', 'CEMENT, HYDRAULIC', 'Manufacturing', 'Metal & Machinery'),
  ('3250', 'STRUCTURAL CLAY PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3260', 'POTTERY & RELATED PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3270', 'CONCRETE, GYPSUM & PLASTER PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3272', 'CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK', 'Manufacturing', 'Metal & Machinery'),
  ('3281', 'CUT STONE & STONE PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3290', 'ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS', 'Manufacturing', 'Metal & Machinery'),
  ('3310', 'STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS', 'Manufacturing', 'Metal & Machinery'),
  ('3312', 'STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)', 'Manufacturing', 'Metal & Machinery'),
  ('3317', 'STEEL PIPE & TUBES', 'Manufacturing', 'Metal & Machinery'),
  ('3320', 'IRON & STEEL FOUNDRIES', 'Manufacturing', 'Metal & Machinery'),
  ('3330', 'PRIMARY SMELTING & REFINING OF NONFERROUS METALS', 'Manufacturing', 'Metal & Machinery'),
  ('3334', 'PRIMARY PRODUCTION OF ALUMINUM', 'Manufacturing', 'Metal & Machinery'),
  ('3341', 'SECONDARY SMELTING & REFINING OF NONFERROUS METALS', 'Manufacturing', 'Metal & Machinery'),
  ('3350', 'ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS', 'Manufacturing', 'Metal & Machinery'),
  ('3357', 'DRAWING & INSULATING OF NONFERROUS WIRE', 'Manufacturing', 'Metal & Machinery'),
  ('3360', 'NONFERROUS FOUNDRIES (CASTINGS)', 'Manufacturing', 'Metal & Machinery'),
  ('3390', 'MISCELLANEOUS PRIMARY METAL PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3411', 'METAL CANS', 'Manufacturing', 'Metal & Machinery'),
  ('3412', 'METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS', 'Manufacturing', 'Metal & Machinery'),
  ('3420', 'CUTLERY, HANDTOOLS & GENERAL HARDWARE', 'Manufacturing', 'Metal & Machinery'),
  ('3430', 'HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES', 'Manufacturing', 'Metal & Machinery'),
  ('3433', 'HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES', 'Manufacturing', 'Metal & Machinery'),
  ('3440', 'FABRICATED STRUCTURAL METAL PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3442', 'METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM', 'Manufacturing', 'Metal & Machinery'),
  ('3443', 'FABRICATED PLATE WORK (BOILER SHOPS)', 'Manufacturing', 'Metal & Machinery'),
  ('3444', 'SHEET METAL WORK', 'Manufacturing', 'Metal & Machinery'),
  ('3448', 'PREFABRICATED METAL BUILDINGS & COMPONENTS', 'Manufacturing', 'Metal & Machinery'),
  ('3451', 'SCREW MACHINE PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3452', 'BOLTS, NUTS, SCREWS, RIVETS & WASHERS', 'Manufacturing', 'Metal & Machinery'),
  ('3460', 'METAL FORGINGS & STAMPINGS', 'Manufacturing', 'Metal & Machinery'),
  ('3470', 'COATING, ENGRAVING & ALLIED SERVICES', 'Manufacturing', 'Metal & Machinery'),
  ('3480', 'ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)', 'Manufacturing', 'Metal & Machinery'),
  ('3490', 'MISCELLANEOUS FABRICATED METAL PRODUCTS', 'Manufacturing', 'Metal & Machinery'),
  ('3510', 'ENGINES & TURBINES', 'Manufacturing', 'Metal & Machinery'),
  ('3523', 'FARM MACHINERY & EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3524', 'LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP', 'Manufacturing', 'Metal & Machinery'),
  ('3530', 'CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP', 'Manufacturing', 'Metal & Machinery'),
  ('3531', 'CONSTRUCTION MACHINERY & EQUIP', 'Manufacturing', 'Metal & Machinery'),
  ('3532', 'MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)', 'Manufacturing', 'Metal & Machinery'),
  ('3533', 'OIL & GAS FIELD MACHINERY & EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3537', 'INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS', 'Manufacturing', 'Metal & Machinery'),
  ('3540', 'METALWORKG MACHINERY & EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3541', 'MACHINE TOOLS, METAL CUTTING TYPES', 'Manufacturing', 'Metal & Machinery'),
  ('3550', 'SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)', 'Manufacturing', 'Metal & Machinery'),
  ('3555', 'PRINTING TRADES MACHINERY & EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3559', 'SPECIAL INDUSTRY MACHINERY, NEC', 'Manufacturing', 'Metal & Machinery'),
  ('3560', 'GENERAL INDUSTRIAL MACHINERY & EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3561', 'PUMPS & PUMPING EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3562', 'BALL & ROLLER BEARINGS', 'Manufacturing', 'Metal & Machinery'),
  ('3564', 'INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP', 'Manufacturing', 'Metal & Machinery'),
  ('3567', 'INDUSTRIAL PROCESS FURNACES & OVENS', 'Manufacturing', 'Metal & Machinery'),
  ('3569', 'GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC', 'Manufacturing', 'Metal & Machinery'),
  ('3570', 'COMPUTER & OFFICE EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3571', 'ELECTRONIC COMPUTERS', 'Manufacturing', 'Metal & Machinery'),
  ('3572', 'COMPUTER STORAGE DEVICES', 'Manufacturing', 'Metal & Machinery'),
  ('3575', 'COMPUTER TERMINALS', 'Manufacturing', 'Metal & Machinery'),
  ('3576', 'COMPUTER COMMUNICATIONS EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3577', 'COMPUTER PERIPHERAL EQUIPMENT, NEC', 'Manufacturing', 'Metal & Machinery'),
  ('3578', 'CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)', 'Manufacturing', 'Metal & Machinery'),
  ('3579', 'OFFICE MACHINES, NEC', 'Manufacturing', 'Metal & Machinery'),
  ('3580', 'REFRIGERATION & SERVICE INDUSTRY MACHINERY', 'Manufacturing', 'Metal & Machinery'),
  ('3585', 'AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP', 'Manufacturing', 'Metal & Machinery'),
  ('3590', 'MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT', 'Manufacturing', 'Metal & Machinery'),
  ('3600', 'ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3612', 'POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3613', 'SWITCHGEAR & SWITCHBOARD APPARATUS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3620', 'ELECTRICAL INDUSTRIAL APPARATUS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3621', 'MOTORS & GENERATORS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3630', 'HOUSEHOLD APPLIANCES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3634', 'ELECTRIC HOUSEWARES & FANS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3640', 'ELECTRIC LIGHTING & WIRING EQUIPMENT', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3651', 'HOUSEHOLD AUDIO & VIDEO EQUIPMENT', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3652', 'PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3661', 'TELEPHONE & TELEGRAPH APPARATUS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3663', 'RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3669', 'COMMUNICATIONS EQUIPMENT, NEC', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3670', 'ELECTRONIC COMPONENTS & ACCESSORIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3672', 'PRINTED CIRCUIT BOARDS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3674', 'SEMICONDUCTORS & RELATED DEVICES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3677', 'ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3678', 'ELECTRONIC CONNECTORS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3679', 'ELECTRONIC COMPONENTS, NEC', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3690', 'MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3695', 'MAGNETIC & OPTICAL RECORDING MEDIA', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3711', 'MOTOR VEHICLES & PASSENGER CAR BODIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3713', 'TRUCK & BUS BODIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3714', 'MOTOR VEHICLE PARTS & ACCESSORIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3715', 'TRUCK TRAILERS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3716', 'MOTOR HOMES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3720', 'AIRCRAFT & PARTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3721', 'AIRCRAFT', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3724', 'AIRCRAFT ENGINES & ENGINE PARTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3728', 'AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3730', 'SHIP & BOAT BUILDING & REPAIRING', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3743', 'RAILROAD EQUIPMENT', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3751', 'MOTORCYCLES, BICYCLES & PARTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3760', 'GUIDED MISSILES & SPACE VEHICLES & PARTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3790', 'MISCELLANEOUS TRANSPORTATION EQUIPMENT', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3812', 'SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3821', 'LABORATORY APPARATUS & FURNITURE', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3822', 'AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3823', 'INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3824', 'TOTALIZING FLUID METERS & COUNTING DEVICES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3825', 'INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3826', 'LABORATORY ANALYTICAL INSTRUMENTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3827', 'OPTICAL INSTRUMENTS & LENSES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3829', 'MEASURING & CONTROLLING DEVICES, NEC', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3841', 'SURGICAL & MEDICAL INSTRUMENTS & APPARATUS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3842', 'ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3843', 'DENTAL EQUIPMENT & SUPPLIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3844', 'X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3845', 'ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3851', 'OPHTHALMIC GOODS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3861', 'PHOTOGRAPHIC EQUIPMENT & SUPPLIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3873', 'WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3910', 'JEWELRY, SILVERWARE & PLATED WARE', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3911', 'JEWELRY, PRECIOUS METAL', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3931', 'MUSICAL INSTRUMENTS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3942', 'DOLLS & STUFFED TOYS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3944', 'GAMES, TOYS & CHILDREN''S VEHICLES (NO DOLLS & BICYCLES)', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3949', 'SPORTING & ATHLETIC GOODS, NEC', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3950', 'PENS, PENCILS & OTHER ARTISTS'' MATERIALS', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3960', 'COSTUME JEWELRY & NOVELTIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('3990', 'MISCELLANEOUS MANUFACTURING INDUSTRIES', 'Manufacturing', 'Electronics & Transportation Equipment'),
  ('4011', 'RAILROADS, LINE-HAUL OPERATING', 'Transportation & Utilities', 'Transportation'),
  ('4013', 'RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS', 'Transportation & Utilities', 'Transportation'),
  ('4100', 'LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS', 'Transportation & Utilities', 'Transportation'),
  ('4210', 'TRUCKING & COURIER SERVICES (NO AIR)', 'Transportation & Utilities', 'Transportation'),
  ('4213', 'TRUCKING (NO LOCAL)', 'Transportation & Utilities', 'Transportation'),
  ('4220', 'PUBLIC WAREHOUSING & STORAGE', 'Transportation & Utilities', 'Transportation'),
  ('4231', 'TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT', 'Transportation & Utilities', 'Transportation'),
  ('4400', 'WATER TRANSPORTATION', 'Transportation & Utilities', 'Transportation'),
  ('4412', 'DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT', 'Transportation & Utilities', 'Transportation'),
  ('4512', 'AIR TRANSPORTATION, SCHEDULED', 'Transportation & Utilities', 'Transportation'),
  ('4513', 'AIR COURIER SERVICES', 'Transportation & Utilities', 'Transportation'),
  ('4522', 'AIR TRANSPORTATION, NONSCHEDULED', 'Transportation & Utilities', 'Transportation'),
  ('4581', 'AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES', 'Transportation & Utilities', 'Transportation'),
  ('4610', 'PIPE LINES (NO NATURAL GAS)', 'Transportation & Utilities', 'Transportation'),
  ('4700', 'TRANSPORTATION SERVICES', 'Transportation & Utilities', 'Transportation'),
  ('4731', 'ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO', 'Transportation & Utilities', 'Transportation'),
  ('4812', 'RADIOTELEPHONE COMMUNICATIONS', 'Transportation & Utilities', 'Communications'),
  ('4813', 'TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)', 'Transportation & Utilities', 'Communications'),
  ('4822', 'TELEGRAPH & OTHER MESSAGE COMMUNICATIONS', 'Transportation & Utilities', 'Communications'),
  ('4832', 'RADIO BROADCASTING STATIONS', 'Transportation & Utilities', 'Communications'),
  ('4833', 'TELEVISION BROADCASTING STATIONS', 'Transportation & Utilities', 'Communications'),
  ('4841', 'CABLE & OTHER PAY TELEVISION SERVICES', 'Transportation & Utilities', 'Communications'),
  ('4899', 'COMMUNICATIONS SERVICES, NEC', 'Transportation & Utilities', 'Communications'),
  ('4900', 'ELECTRIC, GAS & SANITARY SERVICES', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4911', 'ELECTRIC SERVICES', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4922', 'NATURAL GAS TRANSMISSION', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4923', 'NATURAL GAS TRANSMISISON & DISTRIBUTION', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4924', 'NATURAL GAS DISTRIBUTION', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4931', 'ELECTRIC & OTHER SERVICES COMBINED', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4932', 'GAS & OTHER SERVICES COMBINED', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4941', 'WATER SUPPLY', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4950', 'SANITARY SERVICES', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4953', 'REFUSE SYSTEMS', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4955', 'HAZARDOUS WASTE MANAGEMENT', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4961', 'STEAM & AIR-CONDITIONING SUPPLY', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('4991', 'COGENERATION SERVICES & SMALL POWER PRODUCERS', 'Transportation & Utilities', 'Electric, Gas & Sanitary Services'),
  ('5000', 'WHOLESALE-DURABLE GOODS', 'Wholesale Trade', 'Durable Goods'),
  ('5010', 'WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES', 'Wholesale Trade', 'Durable Goods'),
  ('5013', 'WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS', 'Wholesale Trade', 'Durable Goods'),
  ('5020', 'WHOLESALE-FURNITURE & HOME FURNISHINGS', 'Wholesale Trade', 'Durable Goods'),
  ('5030', 'WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS', 'Wholesale Trade', 'Durable Goods'),
  ('5031', 'WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS', 'Wholesale Trade', 'Durable Goods'),
  ('5040', 'WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES', 'Wholesale Trade', 'Durable Goods'),
  ('5045', 'WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE', 'Wholesale Trade', 'Durable Goods'),
  ('5047', 'WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES', 'Wholesale Trade', 'Durable Goods'),
  ('5050', 'WHOLESALE-METALS & MINERALS (NO PETROLEUM)', 'Wholesale Trade', 'Durable Goods'),
  ('5051', 'WHOLESALE-METALS SERVICE CENTERS & OFFICES', 'Wholesale Trade', 'Durable Goods'),
  ('5063', 'WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES', 'Wholesale Trade', 'Durable Goods'),
  ('5064', 'WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS', 'Wholesale Trade', 'Durable Goods'),
  ('5065', 'WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC', 'Wholesale Trade', 'Durable Goods'),
  ('5070', 'WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES', 'Wholesale Trade', 'Durable Goods'),
  ('5072', 'WHOLESALE-HARDWARE', 'Wholesale Trade', 'Durable Goods'),
  ('5080', 'WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES', 'Wholesale Trade', 'Durable Goods'),
  ('5082', 'WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP', 'Wholesale Trade', 'Durable Goods'),
  ('5084', 'WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT', 'Wholesale Trade', 'Durable Goods'),
  ('5090', 'WHOLESALE-MISC DURABLE GOODS', 'Wholesale Trade', 'Durable Goods'),
  ('5094', 'WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS', 'Wholesale Trade', 'Durable Goods'),
  ('5099', 'WHOLESALE-DURABLE GOODS, NEC', 'Wholesale Trade', 'Durable Goods'),
  ('5110', 'WHOLESALE-PAPER & PAPER PRODUCTS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5122', 'WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS'' SUNDRIES', 'Wholesale Trade', 'Nondurable Goods'),
  ('5130', 'WHOLESALE-APPAREL, PIECE GOODS & NOTIONS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5140', 'WHOLESALE-GROCERIES & RELATED PRODUCTS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5141', 'WHOLESALE-GROCERIES, GENERAL LINE', 'Wholesale Trade', 'Nondurable Goods'),
  ('5150', 'WHOLESALE-FARM PRODUCT RAW MATERIALS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5160', 'WHOLESALE-CHEMICALS & ALLIED PRODUCTS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5171', 'WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5172', 'WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)', 'Wholesale Trade', 'Nondurable Goods'),
  ('5180', 'WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES', 'Wholesale Trade', 'Nondurable Goods'),
  ('5190', 'WHOLESALE-MISCELLANEOUS NONDURABLE GOODS', 'Wholesale Trade', 'Nondurable Goods'),
  ('5200', 'RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY', 'Retail Trade', 'Building Materials & Garden'),
  ('5211', 'RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS', 'Retail Trade', 'Building Materials & Garden'),
  ('5271', 'RETAIL-MOBILE HOME DEALERS', 'Retail Trade', 'Building Materials & Garden'),
  ('5311', 'RETAIL-DEPARTMENT STORES', 'Retail Trade', 'General Merchandise'),
  ('5331', 'RETAIL-VARIETY STORES', 'Retail Trade', 'General Merchandise'),
  ('5399', 'RETAIL-MISC GENERAL MERCHANDISE STORES', 'Retail Trade', 'General Merchandise'),
  ('5400', 'RETAIL-FOOD STORES', 'Retail Trade', 'Food Stores'),
  ('5411', 'RETAIL-GROCERY STORES', 'Retail Trade', 'Food Stores'),
  ('5412', 'RETAIL-CONVENIENCE STORES', 'Retail Trade', 'Food Stores'),
  ('5500', 'RETAIL-AUTO DEALERS & GASOLINE STATIONS', 'Retail Trade', 'Automotive & Gas Stations'),
  ('5531', 'RETAIL-AUTO & HOME SUPPLY STORES', 'Retail Trade', 'Automotive & Gas Stations'),
  ('5600', 'RETAIL-APPAREL & ACCESSORY STORES', 'Retail Trade', 'Apparel & Accessories'),
  ('5621', 'RETAIL-WOMEN''S CLOTHING STORES', 'Retail Trade', 'Apparel & Accessories'),
  ('5651', 'RETAIL-FAMILY CLOTHING STORES', 'Retail Trade', 'Apparel & Accessories'),
  ('5661', 'RETAIL-SHOE STORES', 'Retail Trade', 'Apparel & Accessories'),
  ('5700', 'RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES', 'Retail Trade', 'Home Furnishings'),
  ('5712', 'RETAIL-FURNITURE STORES', 'Retail Trade', 'Home Furnishings'),
  ('5731', 'RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES', 'Retail Trade', 'Home Furnishings'),
  ('5734', 'RETAIL-COMPUTER & COMPUTER SOFTWARE STORES', 'Retail Trade', 'Home Furnishings'),
  ('5735', 'RETAIL-RECORD & PRERECORDED TAPE STORES', 'Retail Trade', 'Home Furnishings'),
  ('5810', 'RETAIL-EATING & DRINKING PLACES', 'Retail Trade', 'Eating & Drinking Places'),
  ('5812', 'RETAIL-EATING PLACES', 'Retail Trade', 'Eating & Drinking Places'),
  ('5900', 'RETAIL-MISCELLANEOUS RETAIL', 'Retail Trade', 'Miscellaneous Retail'),
  ('5912', 'RETAIL-DRUG STORES AND PROPRIETARY STORES', 'Retail Trade', 'Miscellaneous Retail'),
  ('5940', 'RETAIL-MISCELLANEOUS SHOPPING GOODS STORES', 'Retail Trade', 'Miscellaneous Retail'),
  ('5944', 'RETAIL-JEWELRY STORES', 'Retail Trade', 'Miscellaneous Retail'),
  ('5945', 'RETAIL-HOBBY, TOY & GAME SHOPS', 'Retail Trade', 'Miscellaneous Retail'),
  ('5960', 'RETAIL-NONSTORE RETAILERS', 'Retail Trade', 'Miscellaneous Retail'),
  ('5961', 'RETAIL-CATALOG & MAIL-ORDER HOUSES', 'Retail Trade', 'Miscellaneous Retail'),
  ('5990', 'RETAIL-RETAIL STORES, NEC', 'Retail Trade', 'Miscellaneous Retail'),
  ('6021', 'NATIONAL COMMERCIAL BANKS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6022', 'STATE COMMERCIAL BANKS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6029', 'COMMERCIAL BANKS, NEC', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6035', 'SAVINGS INSTITUTION, FEDERALLY CHARTERED', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6036', 'SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6099', 'FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6111', 'FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6141', 'PERSONAL CREDIT INSTITUTIONS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6153', 'SHORT-TERM BUSINESS CREDIT INSTITUTIONS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6159', 'MISCELLANEOUS BUSINESS CREDIT INSTITUTION', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6162', 'MORTGAGE BANKERS & LOAN CORRESPONDENTS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6163', 'LOAN BROKERS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6172', 'FINANCE LESSORS', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6189', 'ASSET-BACKED SECURITIES', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6199', 'FINANCE SERVICES', 'Finance, Insurance & Real Estate', 'Banking'),
  ('6200', 'SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES', 'Finance, Insurance & Real Estate', 'Credit Agencies'),
  ('6211', 'SECURITY BROKERS, DEALERS & FLOTATION COMPANIES', 'Finance, Insurance & Real Estate', 'Credit Agencies'),
  ('6221', 'COMMODITY CONTRACTS BROKERS & DEALERS', 'Finance, Insurance & Real Estate', 'Credit Agencies'),
  ('6282', 'INVESTMENT ADVICE', 'Finance, Insurance & Real Estate', 'Credit Agencies'),
  ('6311', 'LIFE INSURANCE', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6321', 'ACCIDENT & HEALTH INSURANCE', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6324', 'HOSPITAL & MEDICAL SERVICE PLANS', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6331', 'FIRE, MARINE & CASUALTY INSURANCE', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6351', 'SURETY INSURANCE', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6361', 'TITLE INSURANCE', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6399', 'INSURANCE CARRIERS, NEC', 'Finance, Insurance & Real Estate', 'Securities & Commodities'),
  ('6411', 'INSURANCE AGENTS, BROKERS & SERVICE', 'Finance, Insurance & Real Estate', 'Insurance'),
  ('6500', 'REAL ESTATE', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6510', 'REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6512', 'OPERATORS OF NONRESIDENTIAL BUILDINGS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6513', 'OPERATORS OF APARTMENT BUILDINGS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6519', 'LESSORS OF REAL PROPERTY, NEC', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6531', 'REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6532', 'REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6552', 'LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6770', 'BLANK CHECKS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6792', 'OIL ROYALTY TRADERS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6794', 'PATENT OWNERS & LESSORS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6795', 'MINERAL ROYALTY TRADERS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6798', 'REAL ESTATE INVESTMENT TRUSTS', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('6799', 'INVESTORS, NEC', 'Finance, Insurance & Real Estate', 'Real Estate'),
  ('7000', 'HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES', 'Services', 'Hotels & Lodging'),
  ('7011', 'HOTELS & MOTELS', 'Services', 'Hotels & Lodging'),
  ('7200', 'SERVICES-PERSONAL SERVICES', 'Services', 'Personal Services'),
  ('7310', 'SERVICES-ADVERTISING', 'Services', 'Business Services'),
  ('7311', 'SERVICES-ADVERTISING AGENCIES', 'Services', 'Business Services'),
  ('7320', 'SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES', 'Services', 'Business Services'),
  ('7330', 'SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY', 'Services', 'Business Services'),
  ('7331', 'SERVICES-DIRECT MAIL ADVERTISING SERVICES', 'Services', 'Business Services'),
  ('7340', 'SERVICES-TO DWELLINGS & OTHER BUILDINGS', 'Services', 'Business Services'),
  ('7350', 'SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING', 'Services', 'Business Services'),
  ('7359', 'SERVICES-EQUIPMENT RENTAL & LEASING, NEC', 'Services', 'Business Services'),
  ('7361', 'SERVICES-EMPLOYMENT AGENCIES', 'Services', 'Business Services'),
  ('7363', 'SERVICES-HELP SUPPLY SERVICES', 'Services', 'Business Services'),
  ('7370', 'SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.', 'Services', 'Business Services'),
  ('7371', 'SERVICES-COMPUTER PROGRAMMING SERVICES', 'Services', 'Business Services'),
  ('7372', 'SERVICES-PREPACKAGED SOFTWARE', 'Services', 'Business Services'),
  ('7373', 'SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN', 'Services', 'Business Services'),
  ('7374', 'SERVICES-COMPUTER PROCESSING & DATA PREPARATION', 'Services', 'Business Services'),
  ('7377', 'SERVICES-COMPUTER RENTAL & LEASING', 'Services', 'Business Services'),
  ('7380', 'SERVICES-MISCELLANEOUS BUSINESS SERVICES', 'Services', 'Business Services'),
  ('7381', 'SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES', 'Services', 'Business Services'),
  ('7384', 'SERVICES-PHOTOFINISHING LABORATORIES', 'Services', 'Business Services'),
  ('7385', 'SERVICES-TELEPHONE INTERCONNECT SYSTEMS', 'Services', 'Business Services'),
  ('7389', 'SERVICES-BUSINESS SERVICES, NEC', 'Services', 'Business Services'),
  ('7500', 'SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING', 'Services', 'Auto Services'),
  ('7510', 'SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)', 'Services', 'Auto Services'),
  ('7600', 'SERVICES-MISCELLANEOUS REPAIR SERVICES', 'Services', 'Miscellaneous Repair Services'),
  ('7812', 'SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION', 'Services', 'Motion Pictures & Entertainment'),
  ('7819', 'SERVICES-ALLIED TO MOTION PICTURE PRODUCTION', 'Services', 'Motion Pictures & Entertainment'),
  ('7822', 'SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION', 'Services', 'Motion Pictures & Entertainment'),
  ('7829', 'SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION', 'Services', 'Motion Pictures & Entertainment'),
  ('7830', 'SERVICES-MOTION PICTURE THEATERS', 'Services', 'Motion Pictures & Entertainment'),
  ('7841', 'SERVICES-VIDEO TAPE RENTAL', 'Services', 'Motion Pictures & Entertainment'),
  ('7900', 'SERVICES-AMUSEMENT & RECREATION SERVICES', 'Services', 'Motion Pictures & Entertainment'),
  ('7948', 'SERVICES-RACING, INCLUDING TRACK OPERATION', 'Services', 'Motion Pictures & Entertainment'),
  ('7990', 'SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION', 'Services', 'Motion Pictures & Entertainment'),
  ('7997', 'SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS', 'Services', 'Motion Pictures & Entertainment'),
  ('8000', 'SERVICES-HEALTH SERVICES', 'Services', 'Health Services'),
  ('8011', 'SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE', 'Services', 'Health Services'),
  ('8050', 'SERVICES-NURSING & PERSONAL CARE FACILITIES', 'Services', 'Health Services'),
  ('8051', 'SERVICES-SKILLED NURSING CARE FACILITIES', 'Services', 'Health Services'),
  ('8060', 'SERVICES-HOSPITALS', 'Services', 'Health Services'),
  ('8062', 'SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC', 'Services', 'Health Services'),
  ('8071', 'SERVICES-MEDICAL LABORATORIES', 'Services', 'Health Services'),
  ('8082', 'SERVICES-HOME HEALTH CARE SERVICES', 'Services', 'Health Services'),
  ('8090', 'SERVICES-MISC HEALTH & ALLIED SERVICES, NEC', 'Services', 'Health Services'),
  ('8093', 'SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC', 'Services', 'Health Services'),
  ('8111', 'SERVICES-LEGAL SERVICES', 'Services', 'Legal Services'),
  ('8200', 'SERVICES-EDUCATIONAL SERVICES', 'Services', 'Educational Services'),
  ('8300', 'SERVICES-SOCIAL SERVICES', 'Services', 'Social Services'),
  ('8351', 'SERVICES-CHILD DAY CARE SERVICES', 'Services', 'Social Services'),
  ('8600', 'SERVICES-MEMBERSHIP ORGANIZATIONS', 'Services', 'Museums & Organizations'),
  ('8700', 'SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT', 'Services', 'Engineering & Management'),
  ('8711', 'SERVICES-ENGINEERING SERVICES', 'Services', 'Engineering & Management'),
  ('8731', 'SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH', 'Services', 'Engineering & Management'),
  ('8734', 'SERVICES-TESTING LABORATORIES', 'Services', 'Engineering & Management'),
  ('8741', 'SERVICES-MANAGEMENT SERVICES', 'Services', 'Engineering & Management'),
  ('8742', 'SERVICES-MANAGEMENT CONSULTING SERVICES', 'Services', 'Engineering & Management'),
  ('8744', 'SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES', 'Services', 'Engineering & Management'),
  ('8880', 'AMERICAN DEPOSITARY RECEIPTS', 'Services', 'Engineering & Management'),
  ('8888', 'FOREIGN GOVERNMENTS', 'Services', 'Engineering & Management'),
  ('8900', 'SERVICES-SERVICES, NEC', 'Services', 'Engineering & Management'),
  ('9721', 'INTERNATIONAL AFFAIRS', 'Public Administration', 'National Security'),
  ('9995', 'NON-OPERATING ESTABLISHMENTS', 'Public Administration', 'National Security')
on conflict (code) do update set description=excluded.description, category=excluded.category, subcategory=excluded.subcategory, updated_at=now();
