-- Load wc_class_codes into the LIVE Supabase schema (project rsg-infrastructure).
-- Additive + idempotent: ON CONFLICT DO NOTHING preserves existing rows,
-- embeddings, notion_id, and curated columns. Run in the Supabase SQL editor.
insert into public.wc_class_codes (wc_code, description, category, subcategory) values
('0005', 'Nursery Employees & Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0006', 'Farm Noc & Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0007', 'Fruit Farm & Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0031', 'Vegetable, Berry Or Grape Farm & Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0034', 'Poultry Farm & Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0035', 'Florist-Cultivating Or Gardening-& Drivers', 'Agriculture & Domestic Services', 'General Operations'),
('0042', 'Landscape Gardening & Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0050', 'Farm Machinery Operation-By Contractor-& Drivers', 'Agriculture & Domestic Services', 'Farm Operations'),
('0106', 'Tree Pruning, Repairing Or Trimming & Drivers', 'Agriculture & Domestic Services', 'Agricultural Services'),
('0251', 'Irrigation Works Operation & Drivers', 'Agriculture & Domestic Services', 'Agricultural Services'),
('0767', 'Non-Ratable Element Code', 'Agriculture & Domestic Services', 'General Operations'),
('0771', 'Non-Ratable Element Code', 'Agriculture & Domestic Services', 'General Operations'),
('0908', 'Domestic Workers-Inside-Occasional', 'Agriculture & Domestic Services', 'Domestic Services'),
('0909', 'Domestic Workers-Outside-Occasional-Including Occasional Chauffeurs', 'Agriculture & Domestic Services', 'Domestic Services'),
('0912', 'Domestic Workers-Outside-Including Private Chauffeurs', 'Agriculture & Domestic Services', 'Domestic Services'),
('0913', 'Domestic Workers-Inside', 'Agriculture & Domestic Services', 'Domestic Services'),
('0917', 'Domestic Service Contractor-Inside', 'Agriculture & Domestic Services', 'Domestic Services'),
('1170', 'Mining Noc-With Shafts, Tunnels Or Drifts-& Drivers', 'Mining & Basic Materials', 'Mining Operations'),
('1320', 'Gas Or Oil Lease Operator-Natural Gas-All Operations-& Drivers', 'Mining & Basic Materials', 'General Operations'),
('1430', 'Smelting, Sintering Or Refining Lead & Drivers', 'Mining & Basic Materials', 'Smelting & Refining'),
('1438', 'Smelting, Sintering Or Refining-Metals-Not Iron Or Lead-Noc-& Drivers', 'Mining & Basic Materials', 'Smelting & Refining'),
('1439', 'Smelting-Electric Process', 'Mining & Basic Materials', 'Smelting & Refining'),
('1452', 'Ore Milling & Drivers', 'Mining & Basic Materials', 'Mining Operations'),
('1463', 'Asphalt Works & Drivers', 'Mining & Basic Materials', 'Stone & Materials Processing'),
('1470', 'Alcohol Mfg.-Wood-& Drivers', 'Mining & Basic Materials', 'General Operations'),
('1624', 'Quarry Noc & Drivers', 'Mining & Basic Materials', 'Mining Operations'),
('1701', 'Cement Mfg.', 'Mining & Basic Materials', 'Stone & Materials Processing'),
('1710', 'Stone Crushing & Drivers', 'Mining & Basic Materials', 'Stone & Materials Processing'),
('1741', 'Flint Or Spar Grinding & Drivers', 'Mining & Basic Materials', 'General Operations'),
('1747', 'Emery Works & Drivers', 'Mining & Basic Materials', 'General Operations'),
('1748', 'Abrasive Wheel Mfg. & Drivers', 'Mining & Basic Materials', 'Stone & Materials Processing'),
('1809', 'Stone Cutting Or Polishing-Marble Or Limestone-& Drivers', 'Mining & Basic Materials', 'General Operations'),
('1810', 'Stone Cutting Or Polishing Noc & Drivers', 'Mining & Basic Materials', 'General Operations'),
('1853', 'Mica Goods Mfg. & Mica Preparing', 'Mining & Basic Materials', 'General Operations'),
('1860', 'Abrasive Paper Or Cloth Preparation', 'Mining & Basic Materials', 'Stone & Materials Processing'),
('1924', 'Wire Drawing-Not Iron Or Steel', 'Mining & Basic Materials', 'General Operations'),
('1925', 'Die Casting Mfg.', 'Mining & Basic Materials', 'General Operations'),
('2001', 'Cookie Mfg.', 'Food, Textile & Manufacturing', 'Food Production'),
('2002', 'Macaroni Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2003', 'Bakery & Route Salespersons, Route Supervisors, Drivers', 'Food, Textile & Manufacturing', 'Food Production'),
('2014', 'Feed Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2021', 'Sugar Refining', 'Food, Textile & Manufacturing', 'Food Production'),
('2039', 'Ice Cream Mfg.& Route Salespersons, Route Supervisors, Drivers', 'Food, Textile & Manufacturing', 'Food Production'),
('2041', 'Candy, Chocolate Or Cocoa Mfg.', 'Food, Textile & Manufacturing', 'Food Production'),
('2065', 'Milk Products Mfg. Noc', 'Food, Textile & Manufacturing', 'Food Production'),
('2070', 'Milk Depot Or Milk Dealer-& Route Salespersons, Route Supervisors, Drivers', 'Food, Textile & Manufacturing', 'Food Production'),
('2081', 'Butchering', 'Food, Textile & Manufacturing', 'General Operations'),
('2089', 'Packing House-All Operations', 'Food, Textile & Manufacturing', 'General Operations'),
('2095', 'Meat Products Mfg. Noc', 'Food, Textile & Manufacturing', 'Food Production'),
('2101', 'Fish Curing', 'Food, Textile & Manufacturing', 'General Operations'),
('2105', 'Fruit Packing', 'Food, Textile & Manufacturing', 'General Operations'),
('2111', 'Cannery Noc', 'Food, Textile & Manufacturing', 'Food Production'),
('2112', 'Fruit Evaporating Or Preserving', 'Food, Textile & Manufacturing', 'General Operations'),
('2114', 'Oyster Processing', 'Food, Textile & Manufacturing', 'General Operations'),
('2121', 'Brewery & Drivers', 'Food, Textile & Manufacturing', 'Food Production'),
('2143', 'Fruit Juice Mfg.-All Operations', 'Food, Textile & Manufacturing', 'General Operations'),
('2150', 'Ice Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2157', 'Bottling Noc & Drivers', 'Food, Textile & Manufacturing', 'General Operations'),
('2172', 'Cigarette, Cigar Or Tobacco Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2211', 'Cotton Batting, Wadding Or Waste Mfg.', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2286', 'Wool Spinning And Weaving', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2288', 'Felt Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2302', 'Silk Thread Or Yarn Mfg.', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2303', 'Silk Throwing And Weaving', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2305', 'Textile Fiber Mfg.-Synthetic', 'Food, Textile & Manufacturing', 'General Operations'),
('2362', 'Knit Goods Mfg. Noc', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2380', 'Net Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2383', 'Carbon Paper Or Typewriter Ribbon Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2387', 'Braid Or Fringe Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2388', 'Embroidery Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2402', 'Carpet Or Rug Mfg. Noc', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2413', 'Textile-Bleaching, Dyeing, Mercerizing, Finishing', 'Food, Textile & Manufacturing', 'General Operations'),
('2416', 'Thread Or Yarn Dyeing Or Finishing', 'Food, Textile & Manufacturing', 'General Operations'),
('2417', 'Cloth Printing', 'Food, Textile & Manufacturing', 'General Operations'),
('2501', 'Clothing Mfg.', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2503', 'Custom Clothing Or Tailor Shop-Alterations-No Mass Mfg., Dry Cleaning Or Laundering', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2534', 'Feather Or Flower Mfg.-Artificial', 'Food, Textile & Manufacturing', 'General Operations'),
('2553', 'Furnishing Goods Mfg. Noc-From Textile Fabrics', 'Food, Textile & Manufacturing', 'General Operations'),
('2570', 'Box Spring Or Mattress Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2571', 'Pillow, Quilt Or Cushion Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2576', 'Awning Or Tent Mfg.-Shop Only', 'Food, Textile & Manufacturing', 'General Operations'),
('2578', 'Bag Or Sack Mfg.-Cloth', 'Food, Textile & Manufacturing', 'General Operations'),
('2590', 'Dry Cleaning-Retail-& Route Salespersons, Drivers', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2591', 'Dry Cleaning Or Laundry Commercial-& Route Salespersons, Drivers', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2593', 'Carpet, Rug Or Upholstery Cleaning-Shop Or Outside-& Route Salespersons, Drivers', 'Food, Textile & Manufacturing', 'Textile Operations'),
('2594', 'Linen, Towel, Uniform Or Apron Rental And Cleaning Company & Route', 'Food, Textile & Manufacturing', 'General Operations'),
('2600', 'Fur Mfg.-Preparing Skins', 'Food, Textile & Manufacturing', 'General Operations'),
('2623', 'Leather Mfg.-Patent Or Enamel', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2640', 'Leather Embossing', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2660', 'Boot Or Shoe Mfg. Noc', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2670', 'Glove Mfg.-Leather Or Textile', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2683', 'Luggage Mfg.', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2688', 'Leather Goods Mfg. Noc', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2689', 'Pocketbook Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2702', 'Logging Or Lumbering & Drivers', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2710', 'Saw Mill', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2714', 'Veneer Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2731', 'Molding Or Planing Mill', 'Food, Textile & Manufacturing', 'General Operations'),
('2735', 'Furniture Stock Mfg.', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2737', 'Door, Sash Or Assembled Millwork Mfg. & Drivers', 'Food, Textile & Manufacturing', 'General Operations'),
('2759', 'Box Or Box Shook Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2790', 'Pattern Making Noc', 'Food, Textile & Manufacturing', 'General Operations'),
('2802', 'Carpentry-Shop Only-& Drivers', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2816', 'Cabinet Work-With Power Machinery', 'Food, Textile & Manufacturing', 'General Operations'),
('2817', 'Cabinet Work-With Power Machinery', 'Food, Textile & Manufacturing', 'General Operations'),
('2818', 'Cabinet Work-With Power Machinery', 'Food, Textile & Manufacturing', 'General Operations'),
('2835', 'Brush Or Broom Mfg. Noc', 'Food, Textile & Manufacturing', 'General Operations'),
('2841', 'Woodenware Mfg. Noc', 'Food, Textile & Manufacturing', 'General Operations'),
('2881', 'Furniture Assembly-Wood-From Manufactured Parts', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2883', 'Furniture Mfg. Noc-Wood', 'Food, Textile & Manufacturing', 'Leather & Wood Products'),
('2913', 'Rattan, Willow Or Twisted Fiber Products Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2916', 'Veneer Products Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('2923', 'Musical Instrument Mfg. Noc-Wood', 'Food, Textile & Manufacturing', 'General Operations'),
('2942', 'Crayon, Pencil Or Penholder Mfg.', 'Food, Textile & Manufacturing', 'General Operations'),
('3004', 'Iron Or Steel-Manufacturing-Steel Making-& Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3018', 'Iron Or Steel-Manufacturing-Rolling Mill-& Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3022', 'Pipe Or Tube Mfg. Noc & Drivers', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3027', 'Rolling Mill Noc & Drivers', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3028', 'Pipe Or Tube Mfg.-Iron Or Steel-& Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3030', 'Iron Or Steel Fabrication -Iron Or Steel Works Shop-Structural-& Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3040', 'Iron Or Steel Fabrication-Iron Or Steel Works Shop-Ornamental-& Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3041', 'Iron Or Steel Fabrication-Iron Or Steel Works Shop-Decorative Or Artistic & Foundries, Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3042', 'Elevator Or Escalator Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3060', 'Door, Door Frame Or Sash Mfg.-Wood-Metal Covered', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3064', 'Sign Mfg. Or Repair-Metal-Shop Only', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3066', 'Sheet Metal Work-Shop Only', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3067', 'Sheet Metal Work-Shop Only', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3076', 'Fireproof Equipment Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3081', 'Foundry Noc-Ferrous', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3085', 'Foundry-Non-Ferrous', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3110', 'Forging Work-Drop Or Machine', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3111', 'Blacksmith', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3113', 'Tool Mfg. Noc-Not Drop Or Machine Forged', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3114', 'Tool Mfg. Noc-Drop Or Machine Forged-Machining Or Finishing Of Tools Or Die Making Operations', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3118', 'Saw Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3122', 'Cutlery Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3126', 'Tool Mfg.-Agricultural, Construction, Logging, Mining, Oil Or Artesian Well', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3129', 'Buckle Or Button Mfg.-Metal', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3132', 'Bolt Or Nut Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3145', 'Automatic Screw Machine Products Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3146', 'Hardware Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3169', 'Stove Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3179', 'Electrical Apparatus Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3188', 'Plumbers'' Supplies Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3190', 'Electric Lighting Fixture, Lantern Or Lamp Mfg.-Assembly & Finishing', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3191', 'Electric Lighting Fixture, Lantern Or Lamp Mfg.-All Other Operations', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3200', 'Arms Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3220', 'Can Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3227', 'Aluminum Ware Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3241', 'Wire Drawing-Iron Or Steel', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3255', 'Wire Cloth Mfg.', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3257', 'Wire Goods Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3270', 'Fastener Mfg.-Metal', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3300', 'Bed Spring Or Wire Mattress Spring Mfg.', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3303', 'Spring Mfg.', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3307', 'Heat Treating-Metal', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3315', 'Brass Or Copper Goods Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3336', 'Type Foundry', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3365', 'Welding Or Cutting Noc & Drivers', 'Metal Works & Heavy Manufacturing', 'Iron & Steel Works'),
('3372', 'Electroplating', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3381', 'Silverware Mfg.', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3383', 'Jewelry Mfg.', 'Metal Works & Heavy Manufacturing', 'Metal Products'),
('3384', 'Precious Stone Setting', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3385', 'Clock Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3400', 'Metal Stamped Products Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3507', 'Agricultural Or Construction Machinery Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3515', 'Textile Machinery Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3548', 'Bookbinding Or Printing Machinery Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3559', 'Confection Machinery Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3561', 'Sewing Machine Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3574', 'Office Computing Or Recording Machine Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3581', 'Fuel Injection Device Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3612', 'Pump Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3620', 'Tank Building-Metal-Shop', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3629', 'Precision Machined Parts Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3632', 'Machine Shop Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3634', 'Valve Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3635', 'Gear Mfg. Or Grinding', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3638', 'Ball Or Roller Bearing Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3642', 'Battery Mfg.-Dry', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3643', 'Electric Power Or Transmission Equipment Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3647', 'Battery Mfg.-Storage', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3648', 'Automobile Lighting, Ignition Or Starting Apparatus Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3681', 'Radio, Telephone Or Television Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3685', 'Instrument Mfg. Noc', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3686', 'Musical Instrument Mfg. Noc-Metal', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3724', 'Machinery Or Equipment Erection Or Installation Noc & Drivers', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3726', 'Boiler Installation Or Repair-Steam', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3737', 'Machinery Or Equipment Repair Or Servicing At Customers'' Premises Noc & Drivers', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3807', 'Automobile Radiator Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3808', 'Automobile Mfg. Or Assembly', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3821', 'Automobile Dismantling & Drivers', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3823', 'Automobile, Bus, Truck Or Trailer Body Mfg.-Riveted Or Welded', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3824', 'Automobile, Bus, Truck Or Trailer Body Mfg.-Noc', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3826', 'Aircraft Engine Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3827', 'Automobile Engine Mfg.', 'Metal Works & Heavy Manufacturing', 'Machinery & Equipment'),
('3830', 'Airplane Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3832', 'Sheet Metal Airplane Parts Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3865', 'Baby Carriage Mfg.', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('3881', 'Car Mfg. - Railroad - & Drivers', 'Metal Works & Heavy Manufacturing', 'General Operations'),
('4000', 'Sand Or Gravel Digging & Drivers', 'Paper, Chemical & Specialized Manufacturing', 'Glass & Ceramics'),
('5000', 'Chimney Construction-Not Metal', 'Construction & Building Trades', 'General Operations'),
('5022', 'Masonry Noc', 'Construction & Building Trades', 'General Construction'),
('5037', 'Painting-Metal Structures-Over Two Stories In Height-& Drivers', 'Construction & Building Trades', 'Specialized Trades'),
('5040', 'Iron Or Steel Erection-Frame Structures', 'Construction & Building Trades', 'General Operations'),
('5057', 'Iron Or Steel Erection Noc', 'Construction & Building Trades', 'General Operations'),
('5059', 'Iron Or Steel Erection-Frame Structures-Not Over Two Stories In Height', 'Construction & Building Trades', 'General Operations'),
('5069', 'Iron Or Steel Erection-Construction Of Dwellings-Not Over Two Stories In Height', 'Construction & Building Trades', 'General Operations'),
('5102', 'Door, Door Frame Or Sash Erection-Metal Or Metal Covered', 'Construction & Building Trades', 'General Operations'),
('5160', 'Elevator Erection Or Repair', 'Construction & Building Trades', 'Specialized Trades'),
('5183', 'Plumbing Noc & Drivers', 'Construction & Building Trades', 'Specialized Trades'),
('5184', 'Boiler Or Steam Pipe Insulating & Drivers', 'Construction & Building Trades', 'General Operations'),
('5188', 'Automatic Sprinkler Installation & Drivers', 'Construction & Building Trades', 'General Operations'),
('5190', 'Electrical Wiring-Within Buildings-& Drivers', 'Construction & Building Trades', 'Specialized Trades'),
('5191', 'Office Machine Installation, Inspection, Adjustment Or Repair', 'Construction & Building Trades', 'General Operations'),
('5192', 'Vending Or Coin Operated Machines-Installation, Service Or Repair-& Rte Sales, Rte Supervsrs, Driver', 'Construction & Building Trades', 'General Operations'),
('5193', 'Oil Or Gas Burner Installation, Service Or Repair & Shop & Drivers', 'Construction & Building Trades', 'General Operations'),
('5213', 'Concrete Construction Noc', 'Construction & Building Trades', 'General Construction'),
('5221', 'Concrete Or Cement Work-Floors, Driveways, Yards Or Sidewalks-& Drivers', 'Construction & Building Trades', 'General Construction'),
('5222', 'Concrete Construction In Connection With Bridges Or Culverts', 'Construction & Building Trades', 'General Construction'),
('5223', 'Swimming Pool Construction-Not Iron Or Steel-& Drivers', 'Construction & Building Trades', 'General Operations'),
('6003', 'Pile Driving Noc & Drivers', 'Heavy Construction & Infrastructure', 'Heavy Construction'),
('6005', 'Breakwater Or Jetty Construction-All Operations To Completion-& Drivers', 'Heavy Construction & Infrastructure', 'General Operations'),
('6017', 'Dam Or Lock Construction-Concrete Work-& Drivers-In Connection With Dams Or Locks-All Types', 'Heavy Construction & Infrastructure', 'General Operations'),
('6018', 'Dam Or Lock Construction-Earth Moving Or Placing-& Drivers-In Connection With Dams Or Locks-All Type', 'Heavy Construction & Infrastructure', 'General Operations'),
('6045', 'Levee Construction-All Operations To Completion-& Drivers', 'Heavy Construction & Infrastructure', 'Heavy Construction'),
('6204', 'Drilling Noc & Drivers', 'Heavy Construction & Infrastructure', 'Specialized Construction'),
('6216', 'Gas Or Oil Lease Work Noc-Natural Gas-By Contractor-& Drivers', 'Heavy Construction & Infrastructure', 'General Operations'),
('6217', 'Excavation Noc & Drivers', 'Heavy Construction & Infrastructure', 'Specialized Construction'),
('6229', 'Irrigation System Construction & Drivers', 'Heavy Construction & Infrastructure', 'General Operations'),
('6233', 'Gas Or Oil Pipeline Construction & Drivers', 'Heavy Construction & Infrastructure', 'Utilities Construction'),
('6235', 'Oil Or Gas Well-Drilling Or Redrilling-& Drivers', 'Heavy Construction & Infrastructure', 'Specialized Construction'),
('6251', 'Tunneling-Not Pneumatic-All Operations', 'Heavy Construction & Infrastructure', 'Heavy Construction'),
('6252', 'Caisson Work-All Operations To Completion', 'Heavy Construction & Infrastructure', 'General Operations'),
('6260', 'Tunneling-Pneumatic-All Operations', 'Heavy Construction & Infrastructure', 'Heavy Construction'),
('6306', 'Sewer Construction-All Operations-& Drivers', 'Heavy Construction & Infrastructure', 'Utilities Construction'),
('6319', 'Gas Main Or Connection Construction & Drivers', 'Heavy Construction & Infrastructure', 'Utilities Construction'),
('6325', 'Conduit Construction-For Cables Or Wires-& Drivers', 'Heavy Construction & Infrastructure', 'Utilities Construction'),
('6400', 'Fence Erection-Metal', 'Heavy Construction & Infrastructure', 'General Operations'),
('7133', 'Railroad-All Employees-& Drivers', 'Transportation & Utilities', 'Ground Transportation'),
('7197', 'Trucking-Parcels Or Packages-Home Delivery From Retail Stores-& Drivers', 'Transportation & Utilities', 'Ground Transportation'),
('7201', 'Boarding Or Livery Stable-Not Sales Stable-& Drivers', 'Transportation & Utilities', 'General Operations'),
('7207', 'Club Or Riding Academy - & Drivers', 'Transportation & Utilities', 'General Operations'),
('7219', 'Trucking Noc-All Employees-& Drivers', 'Transportation & Utilities', 'Ground Transportation'),
('7231', 'Messenger Service Companies-Delivering Mail, Parcels Or Packages- All Employees-& Drivers', 'Transportation & Utilities', 'Ground Transportation'),
('7242', 'Messenger Service Companies-Bicycle Delivery Of Envelopes, Parcels, Or Packages', 'Transportation & Utilities', 'Ground Transportation'),
('7309', 'Stevedoring Noc', 'Transportation & Utilities', 'Marine Operations'),
('7313', 'Coal Dock Operation & Stevedoring', 'Transportation & Utilities', 'Marine Operations'),
('7317', 'Stevedoring-By Hand Or Hand Trucks-Exclusively', 'Transportation & Utilities', 'Marine Operations'),
('7327', 'Stevedoring-Containerized Freight-& Drivers', 'Transportation & Utilities', 'Marine Operations'),
('7333', 'Dredging-All Types-Program I', 'Transportation & Utilities', 'Marine Operations'),
('7335', 'Dredging-All Types-Program Ii-State Act', 'Transportation & Utilities', 'Marine Operations'),
('7337', 'Dredging-All Types-Program Ii-Usl Act', 'Transportation & Utilities', 'Marine Operations'),
('7364', 'Independent Livery Drivers', 'Transportation & Utilities', 'General Operations'),
('7366', 'Freight Handlers On Piers Or In Terminals Or Areas Adjoining Piers', 'Transportation & Utilities', 'General Operations'),
('7367', 'Freight Handlers Noc-State Act Only', 'Transportation & Utilities', 'General Operations'),
('7368', 'Taxicab Or Livery Service-Public-All Other Employees-& Drivers', 'Transportation & Utilities', 'Ground Transportation'),
('7370', 'Ambulance Operation - Volunteer Ambulance Service Company', 'Transportation & Utilities', 'General Operations'),
('7377', 'Limousine Or Livery Service-Private-All Other Employees-& Drivers', 'Transportation & Utilities', 'General Operations'),
('7380', 'Drivers And Helpers Noc-Commercial', 'Transportation & Utilities', 'General Operations'),
('7390', 'Beer Or Ale Dealer-Wholesale-& Drivers', 'Transportation & Utilities', 'General Operations'),
('7394', 'Diving-Marine-Program I', 'Transportation & Utilities', 'Marine Operations'),
('7395', 'Diving-Marine-Program Ii-State Act', 'Transportation & Utilities', 'Marine Operations'),
('7398', 'Diving-Marine-Program Ii-Usl Act', 'Transportation & Utilities', 'Marine Operations'),
('7403', 'Aviation - Aerial Application, Seeding, Herding Or Scintillometer Surveying - All Other Emps. & D', 'Transportation & Utilities', 'Aviation & Utilities'),
('8001', 'Florist Store & Drivers', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8006', 'Grocery Store-Retail-No Fresh Meat', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8008', 'Clothing Or Wearing Apparel Store-Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8012', 'Quick Printing', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8013', 'Jewelry Store', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8016', 'Photocopy Shops-All Employees-& Clerical, Outside Salespersons, Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8017', 'Retail Store Noc-No Service Of Food', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8018', 'Wholesale Store Noc', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8021', 'Meat Dealer-Wholesale', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8025', 'Bicycle Store - Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8031', 'Meat Store-Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8032', 'Clothing Or Wearing Apparel Store-Wholesale', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8033', 'Supermarket-Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8034', 'Grocery Store-Wholesale', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8039', 'Department Store-Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8043', 'Retail Store Noc-Including Service Of Food-Not Restaurants', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8044', 'Furniture Store-Wholesale Or Retail-& Drivers', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8046', 'Automobile Accessories Store Noc-Retail-& Drivers', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8047', 'Drug Store-Wholesale', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8048', 'Fruit Or Vegetable Store-Wholesale', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8068', 'Art Gallery & Clerical', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8069', 'Cellular Telephone Store - Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8072', 'Book Store-Retail', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8090', 'Auctioneers & Salespersons-Outside', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8102', 'Seed Merchant', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8103', 'Wool Merchant & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8105', 'Hide Or Leather Dealer', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8106', 'Iron Or Steel Merchant & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8107', 'Machinery Dealer Noc-Store Or Yard-& Drivers', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8111', 'Plumbers'' Supplies Dealer & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8116', 'Farm Machinery Dealer-All Operations-& Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8199', 'Farm Or Feed Supply Dealer-Retail-Exclusively', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8209', 'Vegetable Packing & Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8215', 'Hay, Grain, Feed Or Fertilizer Dealer-& Local Managers, Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8227', 'Construction Or Erection Permanent Yard', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8232', 'Building Material Dealer-No Second-Hand Material-& Local Managers, Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8235', 'Door, Sash Or Finished Millwork Dealer & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8263', 'Junk Dealer & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8264', 'Bottle, Rubber, Paper Stock Or Rag Dealer-Second-Hand-& Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8265', 'Iron Or Steel Scrap Dealer & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8280', 'Racing Stable & Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8288', 'Livestock Dealer Or Commission Merchant-& Outside Salespersons, Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8291', 'Storage Warehouse-Cold', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8292', 'Storage Warehouse Noc', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8293', 'Furniture Moving And/Or Storage & Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8350', 'Gasoline Or Oil Dealer & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8353', 'Gas Company-Gas Dealer-L.P.G.-All Operations-& Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8381', 'Automobile Gasoline Station -Self-Service Gasoline Exclusively - No Convenience Store', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8382', 'Automobile Gasoline And/Or Service Stations - Self-Service Gasoline Station-With Convenience Store', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8385', 'Bus Company-Garage Employees', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8391', 'Automobile Sales Or Service Agency-All Operations-& Drivers', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8392', 'Automobile Parking Lot & Drivers', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8394', 'Bus Company-All Other Employees & Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8500', 'Metal Scrap Dealer & Drivers', 'Retail, Wholesale & Professional Services', 'Wholesale Trade'),
('8601', 'Engineer Or Architect - Consulting', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8709', 'Stevedoring-Talliers And Checking Clerks Engaged In Connection With Stevedore Work- U.S. Act', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8719', 'Stevedoring-Talliers And Checking Clerks Engaged In Connection With Stevedore Work-State Act Only', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8720', 'Inspection Of Risks For Insurance Or Valuation Purposes Noc', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8723', 'Insurance Companies & Clerical, Salespersons', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8726', 'Steamship Line Or Agency-Port Emps-Superintendents, Capts, Engineers, Stewards & Assts, Pay Clerks', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8731', 'Boiler Inspection', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8742', 'Salespersons, Collectors Or Messengers-Outside', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8745', 'News Agent Or Distributor Of Magazines Or Other Periodicals-Not Retail Dlr-& Outside Salespersons, D', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8747', 'Showroom Salespersons', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8748', 'Automobile Salespersons', 'Retail, Wholesale & Professional Services', 'Retail Operations'),
('8751', 'Route Salespersons And Route Supervisors', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8755', 'Labor Union-All Employees', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8800', 'Mailing Or Addressing Co.', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8802', 'Vinyl Letter Processing', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8803', 'Clerical Service Contractor-Traveling', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8809', 'Executive Officers Noc-Not Foremen, Workers Or Salespersons', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8810', 'Clerical Office Employees Noc', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8820', 'Attorney-All Employees-& Clerical, Messengers, Drivers', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8829', 'Convalescent Or Nursing Home-All Employees', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8831', 'Veterinary Hospital & Drivers', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8832', 'Physician & Clerical', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8833', 'Hospital-Professional Employees', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8835', 'Home, Public and Traveling Healthcare - All Employees', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8837', 'Charitable Organization - All Operation & Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8838', 'Public Library-Professional Employees-Includes Attendants & Ushers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8840', 'Religious House Of Worship-Professional Employees', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8854', 'Health Care Services -Medical Or Other Professional Services-Traveling', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8855', 'Banks and Trust Companies â€” All Employees & Clerical, Outside Salespersons, Drivers', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8857', 'Social Case Workers-Traveling', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8864', 'Developmental Organizations - Incl. Workshop - All Employees & Salespersons, Drivers', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8865', 'Alcohol Or Drug Rehabilitation Facility-All Employees-& Clerical', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8866', 'Assisted Living Facility-All Employees-& Clerical', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8868', 'School-Professional Employees & Clerical', 'Retail, Wholesale & Professional Services', 'Professional Services'),
('8869', 'Day Care Centers-Children-Professional Employees & Clerical, Salespersons', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8871', 'Telecommuter Clerical Employees', 'Retail, Wholesale & Professional Services', 'General Operations'),
('8901', 'Telephone Or Telegraph Co-Office Or Exchange Employees & Clerical', 'Retail, Wholesale & Professional Services', 'General Operations'),
('9014', 'Exterminator & Drivers', 'General Services & Public Administration', 'General Operations'),
('9015', 'Baths', 'General Services & Public Administration', 'General Operations'),
('9016', 'Amusement Park Or Exhibition Operation & Drivers', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9019', 'Bridge Or Vehicular Tunnel Operation & Drivers', 'General Services & Public Administration', 'General Operations'),
('9025', 'Cleaning Outside Surfaces Of Buildings & Drivers', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9026', 'Building Operation-Commercial-No Dwelling Occupancy Except By Owner Or Custodian', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9027', 'Building Operation-Dwelling Or Dwelling/Commercial Occ. No More Than One Story For Comm. Purposes', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9028', 'Building Operation Noc-Dwelling Or Combined Dwelling And Commercial Occupancy', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9029', 'Building Noc-Maintenance Or Ordinary Repair Only-Not Contractors', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9030', 'Building Service Contractor', 'General Services & Public Administration', 'General Operations'),
('9040', 'Hospital-All Other Employees', 'General Services & Public Administration', 'General Operations'),
('9044', 'Hotel-Casino Gambling-All Other Employees-& Outside Salespersons', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9048', 'Camp Operation-Recreational Or Educational-All Employees-& Drivers', 'General Services & Public Administration', 'General Operations'),
('9051', 'Health Care Services-Daily Living Skills Services-Traveling', 'General Services & Public Administration', 'General Operations'),
('9052', 'Hotel Noc-All Other Employees-& Drivers', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9055', 'Exercise Or Health Institute', 'General Services & Public Administration', 'General Operations'),
('9058', 'Hotel Noc-Restaurant Employees', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9059', 'Day Care Centers-Children-All Other Employees-& Drivers', 'General Services & Public Administration', 'General Operations'),
('9060', 'Club-Country, Golf, Fishing Or Yacht-& Clerical', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9061', 'Clubs Noc-All Employees-& Clerical', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9063', 'Ymca, Ywca, Ymha Or Ywha, Institution-All Employees-& Clerical', 'General Services & Public Administration', 'General Operations'),
('9065', 'Club-Tennis-& Clerical', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9071', 'Restaurant-Full-Service-Including Entertainers And/Or Musicians', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9072', 'Restaurant-Fast Food-& Drivers', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9074', 'Bar, Dance Club, Lounge, Nightclub Or Tavern-Including Entertainers And/Or Musicians', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9079', 'Restaurants', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9088', 'Fireworks Exhibition & Drivers', 'General Services & Public Administration', 'General Operations'),
('9089', 'Billiard Hall', 'General Services & Public Administration', 'General Operations'),
('9093', 'Bowling Lane', 'General Services & Public Administration', 'General Operations'),
('9101', 'School Or College-All Other Employees-& Drivers', 'General Services & Public Administration', 'General Operations'),
('9102', 'Park Noc-All Employees-& Drivers', 'General Services & Public Administration', 'General Operations'),
('9108', 'Aviation Aircraft Operation Seat Surcharge', 'General Services & Public Administration', 'General Operations'),
('9111', 'Charitable Organization - Professional Employees & C', 'General Services & Public Administration', 'General Operations'),
('9149', 'Theater-Drive-In-All Employees-& Drivers', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9157', 'Theatrical Prod. In Which Players/ Ents. Dance, Skate, Perform Acrobatics -Players, Ents, Musicians', 'General Services & Public Administration', 'General Operations'),
('9158', 'Theatrical Prod. In Which Players/Ents. Dance, Skate Or Perform Acrobatics -All Other Employees', 'General Services & Public Administration', 'General Operations'),
('9159', 'Theatrical Production Noc-Players, Entertainers Or Musicians', 'General Services & Public Administration', 'General Operations'),
('9160', 'Theatrical Production Noc-All Other Employees', 'General Services & Public Administration', 'General Operations'),
('9178', 'Athletic Team Or Park-Non-Contact Sports', 'General Services & Public Administration', 'General Operations'),
('9179', 'Athletic Team Or Park-Contact Sports', 'General Services & Public Administration', 'General Operations'),
('9180', 'Amusement Device Operation Noc-Not Traveling-& Drivers', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9182', 'Athletic Team Or Park-Operation Of Park-& Drivers', 'General Services & Public Administration', 'General Operations'),
('9186', 'Carnival, Circus Or Amusement Device Operator-Traveling-All Employees-& Drivers', 'General Services & Public Administration', 'Entertainment & Recreation'),
('9220', 'Cemetery Operation & Drivers', 'General Services & Public Administration', 'Public Services'),
('9402', 'Street Cleaning & Drivers', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9403', 'Garbage, Ashes Or Refuse Collection & Drivers', 'General Services & Public Administration', 'General Operations'),
('9410', 'Municipal, Township, County Or State Employee Noc', 'General Services & Public Administration', 'Public Services'),
('9501', 'Painting-Shop Only-& Drivers', 'General Services & Public Administration', 'General Operations'),
('9505', 'Automobile, Bus, Truck Or Trailer Body Mfg.-Painting', 'General Services & Public Administration', 'General Operations'),
('9519', 'Household Appliances-Electrical-Installation, Service Or Repair-& Drivers', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9521', 'House Furnishings Installation Noc & Upholstering', 'General Services & Public Administration', 'General Operations'),
('9522', 'Upholstering', 'General Services & Public Administration', 'General Operations'),
('9526', 'Scaffolds, Hod Hoists, Construction Elevators-Built-Up From Ground-Installation, Rep. Or Removal-& D', 'General Services & Public Administration', 'General Operations'),
('9527', 'Scaffolds-Sidewalk Bridges-Not Over One Story In Height-Installation, Repair Or Removal-& Driver', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9534', 'Mobile Crane And Hoisting Service Contractors Noc & Drivers', 'General Services & Public Administration', 'General Operations'),
('9539', 'Awning, Tent Or Canvas Goods Erection, Removal Or Repair & Drivers', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9545', 'Bill Posting & Drivers', 'General Services & Public Administration', 'General Operations'),
('9549', 'Advertising Co. & Drivers', 'General Services & Public Administration', 'General Operations'),
('9552', 'Sign Erection Or Repair-Away From Shop-Not Outdoor Advertising Companies-& Drivers', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9553', 'Sign Painting Or Lettering On Buildings Or Structures & Drivers', 'General Services & Public Administration', 'General Operations'),
('9585', 'Shoe Repair Shop', 'General Services & Public Administration', 'Building & Maintenance Services'),
('9586', 'Barber Shop', 'General Services & Public Administration', 'General Operations'),
('9600', 'Taxidermist', 'General Services & Public Administration', 'General Operations'),
('9610', 'Motion Picture Production-In Studios Or Outside All Operations Up To The Develop. Of Negatives-& D', 'General Services & Public Administration', 'General Operations'),
('9620', 'Funeral Directors & Drivers', 'General Services & Public Administration', 'General Operations'),
('9984', 'Atomic Energy-Project Work', 'General Services & Public Administration', 'General Operations'),
('9985', 'Atomic Energy-Radiation Exposure NOC', 'General Services & Public Administration', 'General Operations')
on conflict (wc_code) do nothing;
